/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'attachmentIds' : Array<string>,
  'status' : Status,
  'officerRemarks' : [] | [string],
  'workerId' : [] | [string],
  'subject' : string,
  'complaintType' : string,
  'createdAt' : Time,
  'statusDescription' : [] | [string],
  'complaintNumber' : string,
  'updatedAt' : Time,
  'workAddress' : string,
  'complainantName' : string,
  'companyName' : string,
  'details' : string,
  'priority' : Priority,
  'mobile' : string,
  'department' : [] | [string],
  'officer' : [] | [string],
  'incidentDate' : string,
  'nextStep' : [] | [string],
}
export interface ComplaintEditInput {
  'status' : Status,
  'officerRemarks' : [] | [string],
  'workerId' : [] | [string],
  'subject' : string,
  'complaintType' : string,
  'statusDescription' : [] | [string],
  'workAddress' : string,
  'complainantName' : string,
  'companyName' : string,
  'details' : string,
  'priority' : Priority,
  'mobile' : string,
  'department' : [] | [string],
  'officer' : [] | [string],
  'incidentDate' : string,
  'nextStep' : [] | [string],
}
export interface ComplaintInput {
  'attachmentIds' : Array<string>,
  'workerId' : [] | [string],
  'subject' : string,
  'complaintType' : string,
  'workAddress' : string,
  'complainantName' : string,
  'companyName' : string,
  'details' : string,
  'priority' : Priority,
  'mobile' : string,
  'incidentDate' : string,
}
export interface ComplaintStats {
  'resolved' : bigint,
  'total' : bigint,
  'pending' : bigint,
  'urgent' : bigint,
}
export interface Notice {
  'title' : string,
  'content' : string,
  'isImportant' : boolean,
  'createdAt' : Time,
}
export interface NoticeInput {
  'title' : string,
  'content' : string,
  'isImportant' : boolean,
}
export type Priority = { 'normal' : null } |
  { 'urgent' : null } |
  { 'veryUrgent' : null };
export type Status = { 'resolved' : null } |
  { 'pending' : null } |
  { 'investigating' : null } |
  { 'underReview' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotice' : ActorMethod<[NoticeInput], string>,
  'addOfficerRemarks' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignOfficer' : ActorMethod<[string, string, string], undefined>,
  'deleteNotice' : ActorMethod<[string], undefined>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintByNumber' : ActorMethod<[string], Complaint>,
  'getComplaintStats' : ActorMethod<[], ComplaintStats>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitComplaint' : ActorMethod<[ComplaintInput], string>,
  'updateComplaint' : ActorMethod<[string, ComplaintEditInput], undefined>,
  'updateComplaintStatus' : ActorMethod<[string, Status], undefined>,
  'updateComplaintStatusWithDescription' : ActorMethod<
    [string, Status, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];