/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const NoticeInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isImportant' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'investigating' : IDL.Null,
  'underReview' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Priority = IDL.Variant({
  'normal' : IDL.Null,
  'urgent' : IDL.Null,
  'veryUrgent' : IDL.Null,
});
export const Complaint = IDL.Record({
  'attachmentIds' : IDL.Vec(IDL.Text),
  'status' : Status,
  'officerRemarks' : IDL.Opt(IDL.Text),
  'workerId' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'complaintType' : IDL.Text,
  'createdAt' : Time,
  'statusDescription' : IDL.Opt(IDL.Text),
  'complaintNumber' : IDL.Text,
  'updatedAt' : Time,
  'workAddress' : IDL.Text,
  'complainantName' : IDL.Text,
  'companyName' : IDL.Text,
  'details' : IDL.Text,
  'priority' : Priority,
  'mobile' : IDL.Text,
  'department' : IDL.Opt(IDL.Text),
  'officer' : IDL.Opt(IDL.Text),
  'incidentDate' : IDL.Text,
  'nextStep' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ComplaintStats = IDL.Record({
  'resolved' : IDL.Nat,
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'urgent' : IDL.Nat,
});
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isImportant' : IDL.Bool,
  'createdAt' : Time,
});
export const ComplaintInput = IDL.Record({
  'attachmentIds' : IDL.Vec(IDL.Text),
  'workerId' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'complaintType' : IDL.Text,
  'workAddress' : IDL.Text,
  'complainantName' : IDL.Text,
  'companyName' : IDL.Text,
  'details' : IDL.Text,
  'priority' : Priority,
  'mobile' : IDL.Text,
  'incidentDate' : IDL.Text,
});
export const ComplaintEditInput = IDL.Record({
  'status' : Status,
  'officerRemarks' : IDL.Opt(IDL.Text),
  'workerId' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'complaintType' : IDL.Text,
  'statusDescription' : IDL.Opt(IDL.Text),
  'workAddress' : IDL.Text,
  'complainantName' : IDL.Text,
  'companyName' : IDL.Text,
  'details' : IDL.Text,
  'priority' : Priority,
  'mobile' : IDL.Text,
  'department' : IDL.Opt(IDL.Text),
  'officer' : IDL.Opt(IDL.Text),
  'incidentDate' : IDL.Text,
  'nextStep' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotice' : IDL.Func([NoticeInput], [IDL.Text], []),
  'addOfficerRemarks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOfficer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteNotice' : IDL.Func([IDL.Text], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintByNumber' : IDL.Func([IDL.Text], [Complaint], ['query']),
  'getComplaintStats' : IDL.Func([], [ComplaintStats], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func([ComplaintInput], [IDL.Text], []),
  'updateComplaint' : IDL.Func([IDL.Text, ComplaintEditInput], [], []),
  'updateComplaintStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateComplaintStatusWithDescription' : IDL.Func(
      [IDL.Text, Status, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const NoticeInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isImportant' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'investigating' : IDL.Null,
    'underReview' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Priority = IDL.Variant({
    'normal' : IDL.Null,
    'urgent' : IDL.Null,
    'veryUrgent' : IDL.Null,
  });
  const Complaint = IDL.Record({
    'attachmentIds' : IDL.Vec(IDL.Text),
    'status' : Status,
    'officerRemarks' : IDL.Opt(IDL.Text),
    'workerId' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'complaintType' : IDL.Text,
    'createdAt' : Time,
    'statusDescription' : IDL.Opt(IDL.Text),
    'complaintNumber' : IDL.Text,
    'updatedAt' : Time,
    'workAddress' : IDL.Text,
    'complainantName' : IDL.Text,
    'companyName' : IDL.Text,
    'details' : IDL.Text,
    'priority' : Priority,
    'mobile' : IDL.Text,
    'department' : IDL.Opt(IDL.Text),
    'officer' : IDL.Opt(IDL.Text),
    'incidentDate' : IDL.Text,
    'nextStep' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ComplaintStats = IDL.Record({
    'resolved' : IDL.Nat,
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'urgent' : IDL.Nat,
  });
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isImportant' : IDL.Bool,
    'createdAt' : Time,
  });
  const ComplaintInput = IDL.Record({
    'attachmentIds' : IDL.Vec(IDL.Text),
    'workerId' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'complaintType' : IDL.Text,
    'workAddress' : IDL.Text,
    'complainantName' : IDL.Text,
    'companyName' : IDL.Text,
    'details' : IDL.Text,
    'priority' : Priority,
    'mobile' : IDL.Text,
    'incidentDate' : IDL.Text,
  });
  const ComplaintEditInput = IDL.Record({
    'status' : Status,
    'officerRemarks' : IDL.Opt(IDL.Text),
    'workerId' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'complaintType' : IDL.Text,
    'statusDescription' : IDL.Opt(IDL.Text),
    'workAddress' : IDL.Text,
    'complainantName' : IDL.Text,
    'companyName' : IDL.Text,
    'details' : IDL.Text,
    'priority' : Priority,
    'mobile' : IDL.Text,
    'department' : IDL.Opt(IDL.Text),
    'officer' : IDL.Opt(IDL.Text),
    'incidentDate' : IDL.Text,
    'nextStep' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotice' : IDL.Func([NoticeInput], [IDL.Text], []),
    'addOfficerRemarks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOfficer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteNotice' : IDL.Func([IDL.Text], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintByNumber' : IDL.Func([IDL.Text], [Complaint], ['query']),
    'getComplaintStats' : IDL.Func([], [ComplaintStats], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func([ComplaintInput], [IDL.Text], []),
    'updateComplaint' : IDL.Func([IDL.Text, ComplaintEditInput], [], []),
    'updateComplaintStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateComplaintStatusWithDescription' : IDL.Func(
        [IDL.Text, Status, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };