/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NoticeInput {
    title: string;
    content: string;
    isImportant: boolean;
}
export interface ComplaintEditInput {
    status: Status;
    officerRemarks?: string;
    workerId?: string;
    subject: string;
    complaintType: string;
    statusDescription?: string;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: Priority;
    mobile: string;
    department?: string;
    officer?: string;
    incidentDate: string;
    nextStep?: string;
}
export interface Complaint {
    attachmentIds: Array<string>;
    status: Status;
    officerRemarks?: string;
    workerId?: string;
    subject: string;
    complaintType: string;
    createdAt: Time;
    statusDescription?: string;
    complaintNumber: string;
    updatedAt: Time;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: Priority;
    mobile: string;
    department?: string;
    officer?: string;
    incidentDate: string;
    nextStep?: string;
}
export interface Notice {
    title: string;
    content: string;
    isImportant: boolean;
    createdAt: Time;
}
export interface ComplaintStats {
    resolved: bigint;
    total: bigint;
    pending: bigint;
    urgent: bigint;
}
export interface ComplaintInput {
    attachmentIds: Array<string>;
    workerId?: string;
    subject: string;
    complaintType: string;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: Priority;
    mobile: string;
    incidentDate: string;
}
export enum Priority {
    normal = "normal",
    urgent = "urgent",
    veryUrgent = "veryUrgent"
}
export enum Status {
    resolved = "resolved",
    pending = "pending",
    investigating = "investigating",
    underReview = "underReview",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNotice(input: NoticeInput): Promise<string>;
    addOfficerRemarks(complaintNumber: string, remarks: string, nextStep: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignOfficer(complaintNumber: string, officer: string, department: string): Promise<void>;
    deleteNotice(noticeId: string): Promise<void>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaintByNumber(complaintNumber: string): Promise<Complaint>;
    getComplaintStats(): Promise<ComplaintStats>;
    getNotices(): Promise<Array<Notice>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitComplaint(input: ComplaintInput): Promise<string>;
    updateComplaint(complaintNumber: string, input: ComplaintEditInput): Promise<void>;
    updateComplaintStatus(complaintNumber: string, newStatus: Status): Promise<void>;
    updateComplaintStatusWithDescription(complaintNumber: string, newStatus: Status, description: string): Promise<void>;
    deleteNotice(noticeId: string): Promise<void>;
    deleteNews(newsId: string): Promise<void>;
    getNews(): Promise<Array<unknown>>;
    addNews(input: NoticeInput): Promise<string>;
    getAllComplaintsWithPassword(password: string): Promise<Array<Complaint>>;
    getComplaintStatsWithPassword(password: string): Promise<ComplaintStats>;
    updateComplaintStatusWithPassword(password: string, complaintNumber: string, newStatus: Status, description: string): Promise<void>;
    updateComplaintWithPassword(password: string, complaintNumber: string, input: ComplaintEditInput): Promise<void>;
    assignOfficerWithPassword(password: string, complaintNumber: string, officer: string, department: string): Promise<void>;
    addOfficerRemarksWithPassword(password: string, complaintNumber: string, remarks: string, nextStep: string): Promise<void>;
    addNoticeWithPassword(password: string, input: NoticeInput): Promise<string>;
    deleteNoticeWithPassword(password: string, noticeId: string): Promise<void>;
    addNewsWithPassword(password: string, input: NoticeInput): Promise<string>;
    deleteNewsWithPassword(password: string, newsId: string): Promise<void>;
    submitComplaintWithPassword(password: string, input: ComplaintInput): Promise<string>;
}

import type { Complaint as _Complaint, ComplaintEditInput as _ComplaintEditInput, ComplaintInput as _ComplaintInput, Priority as _Priority, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotice(arg0: NoticeInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(arg0);
            return result;
        }
    }
    async addOfficerRemarks(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOfficerRemarks(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOfficerRemarks(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignOfficer(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignOfficer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignOfficer(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteNotice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintByNumber(arg0: string): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintByNumber(arg0);
                return from_candid_Complaint_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintByNumber(arg0);
            return from_candid_Complaint_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintStats(): Promise<ComplaintStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintStats();
            return result;
        }
    }
    async getNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotices();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitComplaint(arg0: ComplaintInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(to_candid_ComplaintInput_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(to_candid_ComplaintInput_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateComplaint(arg0: string, arg1: ComplaintEditInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaint(arg0, to_candid_ComplaintEditInput_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaint(arg0, to_candid_ComplaintEditInput_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateComplaintStatus(arg0: string, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, to_candid_Status_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, to_candid_Status_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateComplaintStatusWithDescription(arg0: string, arg1: Status, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatusWithDescription(arg0, to_candid_Status_n27(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatusWithDescription(arg0, to_candid_Status_n27(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }

    // Password-based admin methods - call actor directly bypassing Candid wrapper
    async getAllComplaintsWithPassword(password: string): Promise<Array<Complaint>> {
        const result = await (this.actor as any).getAllComplaintsWithPassword(password);
        return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
    }

    async getComplaintStatsWithPassword(password: string): Promise<ComplaintStats> {
        const result = await (this.actor as any).getComplaintStatsWithPassword(password);
        return { total: result.total, pending: result.pending, resolved: result.resolved, urgent: result.urgent };
    }

    async getNews(): Promise<Array<unknown>> {
        return (this.actor as any).getNews();
    }

    async addNews(input: NoticeInput): Promise<string> {
        return (this.actor as any).addNews(input);
    }

    async deleteNews(newsId: string): Promise<void> {
        return (this.actor as any).deleteNews(newsId);
    }

    async updateComplaintStatusWithPassword(password: string, complaintNumber: string, newStatus: Status, description: string): Promise<void> {
        return (this.actor as any).updateComplaintStatusWithPassword(password, complaintNumber, to_candid_Status_n27(this._uploadFile, this._downloadFile, newStatus), description);
    }

    async updateComplaintWithPassword(password: string, complaintNumber: string, input: ComplaintEditInput): Promise<void> {
        const candidInput = to_candid_ComplaintEditInput_n25(this._uploadFile, this._downloadFile, input);
        return (this.actor as any).updateComplaintWithPassword(password, complaintNumber, candidInput);
    }

    async assignOfficerWithPassword(password: string, complaintNumber: string, officer: string, department: string): Promise<void> {
        return (this.actor as any).assignOfficerWithPassword(password, complaintNumber, officer, department);
    }

    async addOfficerRemarksWithPassword(password: string, complaintNumber: string, remarks: string, nextStep: string): Promise<void> {
        return (this.actor as any).addOfficerRemarksWithPassword(password, complaintNumber, remarks, nextStep);
    }

    async addNoticeWithPassword(password: string, input: NoticeInput): Promise<string> {
        return (this.actor as any).addNoticeWithPassword(password, input);
    }

    async deleteNoticeWithPassword(password: string, noticeId: string): Promise<void> {
        return (this.actor as any).deleteNoticeWithPassword(password, noticeId);
    }

    async addNewsWithPassword(password: string, input: NoticeInput): Promise<string> {
        return (this.actor as any).addNewsWithPassword(password, input);
    }

    async deleteNewsWithPassword(password: string, newsId: string): Promise<void> {
        return (this.actor as any).deleteNewsWithPassword(password, newsId);
    }
    async submitComplaintWithPassword(password: string, input: ComplaintInput): Promise<string> {
        const result = await (this.actor as any).submitComplaintWithPassword(password, to_candid_ComplaintInput_n21(this._uploadFile, this._downloadFile, input));
        return result;
    }
}
function from_candid_Complaint_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attachmentIds: Array<string>;
    status: _Status;
    officerRemarks: [] | [string];
    workerId: [] | [string];
    subject: string;
    complaintType: string;
    createdAt: _Time;
    statusDescription: [] | [string];
    complaintNumber: string;
    updatedAt: _Time;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: _Priority;
    mobile: string;
    department: [] | [string];
    officer: [] | [string];
    incidentDate: string;
    nextStep: [] | [string];
}): {
    attachmentIds: Array<string>;
    status: Status;
    officerRemarks?: string;
    workerId?: string;
    subject: string;
    complaintType: string;
    createdAt: Time;
    statusDescription?: string;
    complaintNumber: string;
    updatedAt: Time;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: Priority;
    mobile: string;
    department?: string;
    officer?: string;
    incidentDate: string;
    nextStep?: string;
} {
    return {
        attachmentIds: value.attachmentIds,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        officerRemarks: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.officerRemarks)),
        workerId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.workerId)),
        subject: value.subject,
        complaintType: value.complaintType,
        createdAt: value.createdAt,
        statusDescription: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.statusDescription)),
        complaintNumber: value.complaintNumber,
        updatedAt: value.updatedAt,
        workAddress: value.workAddress,
        complainantName: value.complainantName,
        companyName: value.companyName,
        details: value.details,
        priority: from_candid_Priority_n16(_uploadFile, _downloadFile, value.priority),
        mobile: value.mobile,
        department: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.department)),
        officer: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.officer)),
        incidentDate: value.incidentDate,
        nextStep: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.nextStep))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
} | {
    investigating: null;
} | {
    underReview: null;
} | {
    rejected: null;
}): Status {
    return "resolved" in value ? Status.resolved : "pending" in value ? Status.pending : "investigating" in value ? Status.investigating : "underReview" in value ? Status.underReview : "rejected" in value ? Status.rejected : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    urgent: null;
} | {
    veryUrgent: null;
}): Priority {
    return "normal" in value ? Priority.normal : "urgent" in value ? Priority.urgent : "veryUrgent" in value ? Priority.veryUrgent : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ComplaintEditInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintEditInput): _ComplaintEditInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ComplaintInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComplaintInput): _ComplaintInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attachmentIds: Array<string>;
    workerId?: string;
    subject: string;
    complaintType: string;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: Priority;
    mobile: string;
    incidentDate: string;
}): {
    attachmentIds: Array<string>;
    workerId: [] | [string];
    subject: string;
    complaintType: string;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: _Priority;
    mobile: string;
    incidentDate: string;
} {
    return {
        attachmentIds: value.attachmentIds,
        workerId: value.workerId ? candid_some(value.workerId) : candid_none(),
        subject: value.subject,
        complaintType: value.complaintType,
        workAddress: value.workAddress,
        complainantName: value.complainantName,
        companyName: value.companyName,
        details: value.details,
        priority: to_candid_Priority_n23(_uploadFile, _downloadFile, value.priority),
        mobile: value.mobile,
        incidentDate: value.incidentDate
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    officerRemarks?: string;
    workerId?: string;
    subject: string;
    complaintType: string;
    statusDescription?: string;
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: Priority;
    mobile: string;
    department?: string;
    officer?: string;
    incidentDate: string;
    nextStep?: string;
}): {
    status: _Status;
    officerRemarks: [] | [string];
    workerId: [] | [string];
    subject: string;
    complaintType: string;
    statusDescription: [] | [string];
    workAddress: string;
    complainantName: string;
    companyName: string;
    details: string;
    priority: _Priority;
    mobile: string;
    department: [] | [string];
    officer: [] | [string];
    incidentDate: string;
    nextStep: [] | [string];
} {
    return {
        status: to_candid_Status_n27(_uploadFile, _downloadFile, value.status),
        officerRemarks: value.officerRemarks ? candid_some(value.officerRemarks) : candid_none(),
        workerId: value.workerId ? candid_some(value.workerId) : candid_none(),
        subject: value.subject,
        complaintType: value.complaintType,
        statusDescription: value.statusDescription ? candid_some(value.statusDescription) : candid_none(),
        workAddress: value.workAddress,
        complainantName: value.complainantName,
        companyName: value.companyName,
        details: value.details,
        priority: to_candid_Priority_n23(_uploadFile, _downloadFile, value.priority),
        mobile: value.mobile,
        department: value.department ? candid_some(value.department) : candid_none(),
        officer: value.officer ? candid_some(value.officer) : candid_none(),
        incidentDate: value.incidentDate,
        nextStep: value.nextStep ? candid_some(value.nextStep) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    normal: null;
} | {
    urgent: null;
} | {
    veryUrgent: null;
} {
    return value == Priority.normal ? {
        normal: null
    } : value == Priority.urgent ? {
        urgent: null
    } : value == Priority.veryUrgent ? {
        veryUrgent: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    resolved: null;
} | {
    pending: null;
} | {
    investigating: null;
} | {
    underReview: null;
} | {
    rejected: null;
} {
    return value == Status.resolved ? {
        resolved: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.investigating ? {
        investigating: null
    } : value == Status.underReview ? {
        underReview: null
    } : value == Status.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
